// Elbaf Gaming - 50 Games Database (English Edition)
// Loaded globally via <script> to ensure maximum compatibility with both file:// and http:// protocols.

const GAMES_DATA = [
  {
    id: 1,
    name: "Red Dead Redemption II",
    category: "action-rpg",
    price: 60,
    platform: "PC / PS5 / Xbox Series X",
    year: "2018",
    developer: "Rockstar Games",
    esrb: "M (Mature)",
    cpu: "Intel Core i7-4770 / AMD FX-8350",
    gpu: "NVIDIA GTX 1060 6GB / AMD RX 480 4GB",
    ram: "12 GB RAM",
    storage: "150 GB available space",
    desc: "Play as Arthur Morgan, an outlaw fighting to survive with his gang in the final years of the Wild West. Experience a massive, stunning, open-world adventure filled with lawmen, outlaws, and dynamic natural wildlife.",
    image: "https://i.ytimg.com/vi/eaW0tYpxyp0/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDfZCf-3KxB5YOHfSmdTCSK7OubhQ",
    rating: 4.9,
    licensePattern: "RDR2-MORG-AN99-WILD-WEST"
  },
  {
    id: 2,
    name: "Resident Evil Requiem",
    category: "horror",
    price: 52,
    platform: "PC / PS5",
    year: "2025",
    developer: "Capcom",
    esrb: "M (Mature)",
    cpu: "Intel Core i7-8700 / AMD Ryzen 5 3600",
    gpu: "NVIDIA RTX 2070 / AMD Radeon RX 5700 XT",
    ram: "16 GB RAM",
    storage: "60 GB available space",
    desc: "Resident Evil Requiem is a survival horror game filled with terrifying creatures, dark mysteries, and intense action. Explore dangerous locations, solve puzzles, and fight to survive in a world consumed by fear and chaos.",
    image: "https://wallpaperaccess.com/full/23972974.jpg",
    rating: 4.8,
    licensePattern: "RE-REQU-IEM7-VACC-INE8"
  },
  {
    id: 3,
    name: "Hollow Knight",
    category: "action-rpg",
    price: 6,
    platform: "PC / Nintendo Switch",
    year: "2017",
    developer: "Team Cherry",
    esrb: "E10+ (Everyone 10+)",
    cpu: "Intel Core i3",
    gpu: "NVIDIA GeForce GTX 560",
    ram: "4 GB RAM",
    storage: "9 GB available space",
    desc: "Forge your own path in Hollow Knight! An epic action-adventure through a vast ruined kingdom of insects and heroes. Explore twisting caverns, battle tainted creatures and befriend bizarre bugs, all in a classic, hand-drawn 2D style.",
    image: "https://4kwallpapers.com/images/wallpapers/hollow-knight--25418.jpg",
    rating: 4.9,
    licensePattern: "HK-HOLL-OWKN-IGHT-VOID"
  },
  {
    id: 4,
    name: "Mafia: The Old Country",
    category: "action-rpg",
    price: 52,
    platform: "PC / PS5 / Xbox Series X",
    year: "2025",
    developer: "Hangar 13",
    esrb: "M (Mature)",
    cpu: "Intel Core i5-10400F / AMD Ryzen 5 3600",
    gpu: "NVIDIA GTX 1660 Super / AMD RX 5600 XT",
    ram: "16 GB RAM",
    storage: "80 GB available space",
    desc: "Unearth the origins of organized crime in Mafia: The Old Country, a gritty mob story set in the brutal underworld of 1900s Sicily. Fight to survive in this dangerous era, with linear, narrative-focused mobster action.",
    image: "https://images.steamusercontent.com/ugc/11917605549148104/D9ECF60463518AEDE5166924047558413E95C1CA/?imw=512&imh=293&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=true",
    rating: 4.7,
    licensePattern: "MAFI-AOLD-COUN-TRY-DON4"
  },
  {
    id: 5,
    name: "Elden Ring",
    category: "action-rpg",
    price: 34,
    platform: "PC / PS5 / Xbox Series X",
    year: "2022",
    developer: "FromSoftware",
    esrb: "M (Mature)",
    cpu: "Intel Core i5-8400 / AMD Ryzen 3 3300X",
    gpu: "NVIDIA GTX 1060 3GB / AMD RX 580 4GB",
    ram: "12 GB RAM",
    storage: "60 GB available space",
    desc: "Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between. Explore massive castles and vast field plains in a legendary world crafted by Hidetaka Miyazaki and George R. R. Martin.",
    image: "https://i.ytimg.com/vi/gyn8bpuixDI/hq720.jpg?sqp=-oaymwE7CK4FEIIDSFryq4qpAy0IARUAAAAAGAElAADIQj0AgKJD8AEB-AH-CYAC0AWKAgwIABABGA8gZShMMA8=&rs=AOn4CLDH3NWsvU_AzcvucgcPzz4-5taZ_Q",
    rating: 4.9,
    licensePattern: "ELDN-RING-GRAC-ETAR-NISH"
  },
  {
    id: 6,
    name: "EA Sports FC 26",
    category: "sports",
    price: 40,
    platform: "PC / PS5 / Xbox Series X / Switch",
    year: "2025",
    developer: "EA Sports",
    esrb: "E (Everyone)",
    cpu: "Intel Core i5-6600K / AMD Ryzen 5 1600",
    gpu: "NVIDIA GTX 1050 Ti / AMD RX 570",
    ram: "8 GB RAM",
    storage: "50 GB available space",
    desc: "EA Sports FC 26 brings realistic football simulation with hyper-advanced HyperMotion gameplay, refreshed career modes, and customizable clubs. Play with the absolute best clubs, leagues, and star athletes worldwide.",
    image: "https://pbs.twimg.com/media/Gn-1RxwW8AA-R4t.jpg",
    rating: 4.5,
    licensePattern: "FC26-FOOT-BALL-CLUB-GOAL"
  },
  {
    id: 7,
    name: "Call of Duty: Black Ops 6",
    category: "action-rpg",
    price: 60,
    platform: "PC / PS5 / Xbox Series X",
    year: "2024",
    developer: "Activision",
    esrb: "M (Mature)",
    cpu: "Intel Core i5-9600K / AMD Ryzen 5 3600X",
    gpu: "NVIDIA GTX 1080 / AMD RX 5700",
    ram: "16 GB RAM",
    storage: "120 GB available space",
    desc: "Step into intense action with Call of Duty, featuring theatrical single-player campaign structures, high-performance competitive multiplayer matches, and massive survival mode maps.",
    image: "https://wallpapercg.com/media/ts_orig/26596.webp",
    rating: 4.6,
    licensePattern: "CODB-OPS6-TACT-ICAL-STRI"
  },
  {
    id: 8,
    name: "Grand Theft Auto V Enhanced",
    category: "action-rpg",
    price: 30,
    platform: "PC / PS5 / Xbox Series X",
    year: "2022",
    developer: "Rockstar Games",
    esrb: "M (Mature)",
    cpu: "Intel Core i5-4460 / AMD FX-8350",
    gpu: "NVIDIA GTX 760 / AMD HD 7870",
    ram: "8 GB RAM",
    storage: "90 GB available space",
    desc: "Experience the blockbuster open-world game, now enhanced for modern hardware. Explore the sprawling city of Los Santos and Blaine County through the intertwined stories of three distinct criminals pulling off daring heists.",
    image: "https://c4.wallpaperflare.com/wallpaper/405/24/958/gta-v-hd-wallpaper-wallpaper-preview.jpg",
    rating: 4.8,
    licensePattern: "GTAV-HEIS-TPLN-LSAN-TOS9"
  },
  {
    id: 9,
    name: "ONE PIECE: PIRATE WARRIORS 4",
    category: "anime",
    price: 26,
    platform: "PC / PS4 / Xbox One / Switch",
    year: "2020",
    developer: "Koei Tecmo",
    esrb: "T (Teen)",
    cpu: "Intel Core i5-3470",
    gpu: "NVIDIA GeForce GTX 660",
    ram: "8 GB RAM",
    storage: "40 GB available space",
    desc: "Join Luffy and the Straw Hat Pirates on a massive field-battling odyssey! Blast away thousands of enemies with colossal anime attacks, experiencing stories directly from the Wano Arc and beyond.",
    image: "https://us-east-1-bandai.graphassets.com/AXzioIclSWilEjFtsMJPwz/ZEelQEdGSOKWR30uVuU8",
    rating: 4.7,
    licensePattern: "OPPW-GEAR-FIVE-WANO-LUFF"
  },
  {
    id: 10,
    name: "NARUTO SHIPPUDEN: STORM 4",
    category: "anime",
    price: 12,
    platform: "PC / PS4 / Xbox One / Switch",
    year: "2016",
    developer: "CyberConnect2",
    esrb: "T (Teen)",
    cpu: "Intel Core i3",
    gpu: "NVIDIA GeForce GTX 750 Ti",
    ram: "4 GB RAM",
    storage: "40 GB available space",
    desc: "Experience the ultimate Ninja showdown! Features beautiful, highly fast anime arena fighting, a rich story mode chronicling the Fourth Great Ninja War, and an expansive roster of legendary Naruto ninjas.",
    image: "https://wallpapercave.com/wp/wp2419004.jpg",
    rating: 4.8,
    licensePattern: "NSTS-NINJ-AWAR-RASN-GANN"
  },
  {
    id: 11,
    name: "DRAGON BALL: Sparking! ZERO",
    category: "anime",
    price: 64,
    platform: "PC / PS5 / Xbox Series X",
    year: "2024",
    developer: "Spike Chunsoft",
    esrb: "T (Teen)",
    cpu: "Intel Core i5-9600K / AMD Ryzen 5 2600",
    gpu: "NVIDIA GTX 980 / AMD RX 590",
    ram: "8 GB RAM",
    storage: "50 GB available space",
    desc: "DRAGON BALL: Sparking! ZERO takes the legendary gameplay of the Budokai Tenkaichi series and elevates it to historic heights. Unleash earth-shattering power with a massive roster of Super Saiyans, villains, and gods.",
    image: "https://images5.alphacoders.com/137/thumb-1920-1379692.jpg",
    rating: 4.9,
    licensePattern: "DBZK-SPAR-KING-ZERO-GOKU"
  },
  {
    id: 12,
    name: "HITMAN World of Assassination",
    category: "action-rpg",
    price: 14,
    platform: "PC / PS5 / Xbox Series X",
    year: "2021",
    developer: "IO Interactive",
    esrb: "M (Mature)",
    cpu: "Intel Core i5-2500K / AMD Phenom II X4",
    gpu: "NVIDIA GTX 660 / AMD Radeon HD 7870",
    ram: "8 GB RAM",
    storage: "80 GB available space",
    desc: "Become Agent 47, the world's ultimate assassin. Travel to premium locations across the globe to eliminate high-profile targets with ultimate freedom, stealth, and tactical options.",
    image: "https://wallpapercave.com/wp/wp14144887.jpg",
    rating: 4.7,
    licensePattern: "HITM-ASSS-ASIN-SILN-T47X"
  },
  {
    id: 13,
    name: "Batman: Arkham Collection",
    category: "action-rpg",
    price: 59,
    platform: "PC / PS4 / Xbox One",
    year: "2018",
    developer: "Rocksteady Studios",
    esrb: "M (Mature)",
    cpu: "Intel Core i5-3570K",
    gpu: "NVIDIA GeForce GTX 660",
    ram: "8 GB RAM",
    storage: "100 GB available space",
    desc: "Experience Rocksteady's award-winning Arkham trilogy in its complete glory. Featuring deep, visceral combat, immersive gadget-driven investigations, and legendary voice acting with Mark Hamill as the Joker.",
    image: "https://image.api.playstation.com/vulcan/ap/rnd/202306/0915/33a2bc694cae0b6ea1210602a36360427af8486f3b10c0d4.jpg?w=440",
    rating: 4.9,
    licensePattern: "BATM-ARKH-AMTR-ILGY-DARK"
  },
  {
    id: 14,
    name: "Spider-Man Remastered",
    category: "action-rpg",
    price: 59,
    platform: "PC / PS5",
    year: "2022",
    developer: "Insomniac Games",
    esrb: "T (Teen)",
    cpu: "Intel Core i3-4160 / AMD Ryzen 3 1200",
    gpu: "NVIDIA GTX 950 / AMD RX 460",
    ram: "8 GB RAM",
    storage: "75 GB available space",
    desc: "Play as Peter Parker and fight crime in a stunning, fully-realized Manhattan. Swing seamlessly between skyscrapers, use high-tech gadgets, and enjoy visual remaster enhancements with ray-tracing features.",
    image: "https://wallpapercave.com/wp/wp7593605.jpg",
    rating: 4.8,
    licensePattern: "SPID-ERMA-NREM-ASTE-RED8"
  },
  {
    id: 15,
    name: "Assassin's Creed Black Flag Resynced",
    category: "action-rpg",
    price: 47,
    platform: "PC / PS5 / Xbox Series X",
    year: "2026",
    developer: "Ubisoft",
    esrb: "M (Mature)",
    cpu: "Intel Core i5-11400 / AMD Ryzen 5 5600",
    gpu: "NVIDIA RTX 3060 / AMD RX 6600",
    ram: "16 GB RAM",
    storage: "60 GB available space",
    desc: "Command the Jackdaw and conquer the Caribbean seas. Live the life of pirate assassin Edward Kenway, now fully re-synced with next-generation engine lighting, realistic naval physics, and expanded stealth missions.",
    image: "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/af7dfb2d-8cc1-45ab-9bab-6b0d0c655e58/dlwwq1d-f6bc9c79-08d2-4a13-874a-70f70cb2491b.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiIvZi9hZjdkZmIyZC04Y2MxLTQ1YWItOWJhYi02YjBkMGM2NTVlNTgvZGx3d3ExZC1mNmJjOWM3OS0wOGQyLTRhMTMtODc0YS03MGY3MGNiMjQ5MWIuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.S5iWbpxEl47tMChB5C6wZyF0hN8W1fuXwUTm8prWSII",
    rating: 4.8,
    licensePattern: "ACBF-PIRA-TESX-SEAS-JACK"
  },
  {
    id: 16,
    name: "Dying Light: The Beast",
    category: "horror",
    price: 56,
    platform: "PC / PS5 / Xbox Series X",
    year: "2025",
    developer: "Techland",
    esrb: "M (Mature)",
    cpu: "Intel Core i5-12400 / AMD Ryzen 5 5600",
    gpu: "NVIDIA RTX 3070 / AMD RX 6750 XT",
    ram: "16 GB RAM",
    storage: "70 GB available space",
    desc: "Dying Light: The Beast is a thrilling zombie survival action game. Vault across decaying urban ruins with smooth parkour, craft unique weapons, and beware the horrors that hunt you when the sun sets.",
    image: "https://xboxwire.thesourcemediaassets.com/sites/2/2025/06/Dying-Light_-The-Beast-key-visual-ENG-ea4991b13af607f23ee6.jpg",
    rating: 4.6,
    licensePattern: "DLTB-BEAS-TMOD-ZOMB-HUNT"
  },
  {
    id: 17,
    name: "Devil May Cry HD Collection",
    category: "action-rpg",
    price: 22,
    platform: "PC / PS4 / Xbox One",
    year: "2018",
    developer: "Capcom",
    esrb: "M (Mature)",
    cpu: "Intel Core i3",
    gpu: "NVIDIA GeForce GTX 760",
    ram: "4 GB RAM",
    storage: "12 GB available space",
    desc: "Command legendary half-demon hunter Dante in the definitive bundle. Features Dante's premier style-ranked battles through Devil May Cry 1, 2, and 3: Special Edition.",
    image: "https://www.psu.com/wp/wp-content/uploads/2017/12/DevilMayCryHDCollection-1024x768.jpg",
    rating: 4.8,
    licensePattern: "DMCH-DCOL-LECT-IONR-DANT"
  },
  {
    id: 18,
    name: "NINJA GAIDEN 4",
    category: "anime",
    price: 47,
    platform: "PC / PS5 / Xbox Series X",
    year: "2026",
    developer: "Team Ninja",
    esrb: "M (Mature)",
    cpu: "Intel Core i5-11400 / AMD Ryzen 5 5600",
    gpu: "NVIDIA RTX 3060 / AMD RX 6600",
    ram: "16 GB RAM",
    storage: "50 GB available space",
    desc: "Step back into the shadow boots of Dragon Ninja Ryu Hayabusa. Engage in lightning-fast ninja combat, sever monstrous beasts with legendary weapons, and explore gorgeous historical cyber-arenas.",
    image: "https://www.platinumgames.com/official-blog/wp-content/uploads/sites/2/2025/10/Matador_Blog_02-01-1024x576.png",
    rating: 4.7,
    licensePattern: "NJGD-RYUH-AYAB-USAN-INJ4"
  },
  {
    id: 19,
    name: "Resident Evil 4 Remake",
    category: "horror",
    price: 29,
    platform: "PC / PS5 / Xbox Series X",
    year: "2023",
    developer: "Capcom",
    esrb: "M (Mature)",
    cpu: "Intel Core i5-7500 / AMD Ryzen 3 1200",
    gpu: "NVIDIA GTX 1050 Ti / AMD RX 560",
    ram: "8 GB RAM",
    storage: "60 GB available space",
    desc: "Survival is just the beginning. Special Agent Leon S. Kennedy travels to a secluded European village to rescue the President's kidnapped daughter, discovering a terrifying cult infected with local parasites.",
    image: "https://www.psu.com/wp/wp-content/uploads/2022/06/ResidentEvil4-Remake-PS5-Wallpapers-0.jpg",
    rating: 4.9,
    licensePattern: "RE4R-LEON-KENN-EDYY-RESC"
  },
  {
    id: 20,
    name: "The Last of Us Part I",
    category: "horror",
    price: 59,
    platform: "PC / PS5",
    year: "2022",
    developer: "Naughty Dog",
    esrb: "M (Mature)",
    cpu: "Intel Core i7-4770K / AMD Ryzen 5 1500X",
    gpu: "NVIDIA GTX 970 / AMD RX 470",
    ram: "16 GB RAM",
    storage: "100 GB available space",
    desc: "Relive the emotional, acclaimed story of survival. In a ravaged civilization infested with fungal spores and hostile survivors, tired smuggler Joel is hired to escort 14-year-old Ellie across a post-apocalyptic United States.",
    image: "https://images3.alphacoders.com/129/1295037.jpg",
    rating: 4.9,
    licensePattern: "TLOU-JOEL-ELLI-EARR-IVALL"
  },
  {
    id: 21,
    name: "DEATH STRANDING 2: ON THE BEACH",
    category: "action-rpg",
    price: 70,
    platform: "PC / PS5",
    year: "2025",
    developer: "Kojima Productions",
    esrb: "M (Mature)",
    cpu: "Intel Core i7-9700K / AMD Ryzen 7 3700X",
    gpu: "NVIDIA RTX 2080 / AMD RX 6800",
    ram: "16 GB RAM",
    storage: "90 GB available space",
    desc: "Embark on an inspiring next-generation journey of connections with Sam Porter Bridges and Fragile. Traverse cinematic post-apocalyptic landscapes, rebuild societal grids, and encounter stunning cosmic anomalies.",
    image: "https://preview.redd.it/death-stranding-2-on-the-beach-new-key-art-screenshots-v0-v11ggtndd5oe1.png?width=3840&format=png&auto=webp&s=e898fd0f809784102ace9c2b526ff87dbf51fa36",
    rating: 4.8,
    licensePattern: "DS2O-NTHE-BEAC-HKOJ-IMAX"
  },
  {
    id: 22,
    name: "God of War Ragnarök",
    category: "action-rpg",
    price: 49,
    platform: "PC / PS5 / PS4",
    year: "2022",
    developer: "Santa Monica Studio",
    esrb: "M (Mature)",
    cpu: "Intel Core i5-4670K / AMD Ryzen 3 1200",
    gpu: "NVIDIA GTX 1060 6GB / AMD RX 570",
    ram: "8 GB RAM",
    storage: "110 GB available space",
    desc: "Join Kratos and Atreus on a legendary Norse journey through all Nine Realms as Asgardian forces prepare for the predicted end of the world. Wield the Leviathan Axe and Blades of Chaos in savage mythological warfare.",
    image: "https://4kwallpapers.com/images/wallpapers/god-of-war-ragnarok-kratos-atreus-2022-games-playstation-4-3840x2160-8636.jpg",
    rating: 4.9,
    licensePattern: "GOWR-KRAT-OSAT-REUS-VALH"
  },
  {
    id: 23,
    name: "Black Myth: Wukong",
    category: "action-rpg",
    price: 60,
    platform: "PC / PS5 / Xbox Series X",
    year: "2024",
    developer: "Game Science",
    esrb: "T (Teen)",
    cpu: "Intel Core i5-8400 / AMD Ryzen 5 1600",
    gpu: "NVIDIA GTX 1060 6GB / AMD RX 580",
    ram: "16 GB RAM",
    storage: "130 GB available space",
    desc: "Embark on an action-RPG journey inspired by the classical Chinese epic 'Journey to the West'. Control the Destined One, master staff-fighting, cast mystical spells, and battle legendary mythological beasts.",
    image: "https://4kwallpapers.com/images/walls/thumbs_2t/18201.jpg",
    rating: 4.9,
    licensePattern: "BMWK-MONK-EYKI-NGST-AFF5"
  },
  {
    id: 24,
    name: "Crimson Desert",
    category: "action-rpg",
    price: 71,
    platform: "PC / PS5 / Xbox Series X",
    year: "2025",
    developer: "Pearl Abyss",
    esrb: "M (Mature)",
    cpu: "Intel Core i7-8700K / AMD Ryzen 5 3600",
    gpu: "NVIDIA RTX 2060 / AMD RX 5700",
    ram: "16 GB RAM",
    storage: "80 GB available space",
    desc: "Fight to reclaim land in the brutal continent of Pywel. Guide a band of mercenaries through heavy sword-slashing battles, command fortresses, and experience a massive story of betrayal.",
    image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80",
    rating: 4.6,
    licensePattern: "CRDS-MERC-ENAR-YWAR-PYWL"
  },
  {
    id: 25,
    name: "Cyberpunk 2077",
    category: "action-rpg",
    price: 45,
    platform: "PC / PS5 / Xbox Series X",
    year: "2020",
    developer: "CD Projekt Red",
    esrb: "M (Mature)",
    cpu: "Intel Core i7-6700 / AMD Ryzen 5 1600",
    gpu: "NVIDIA GTX 1060 6GB / AMD RX 580",
    ram: "12 GB RAM",
    storage: "70 GB available space",
    desc: "Become V, a cybernetically-enhanced outlaw merc in Night City. Wield customized high-tech chrome upgrades, explore immersive neon districts, and fight for a chip that holds the key to immortality.",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    licensePattern: "CP77-CHRO-MEPU-NKVV-NEON"
  },
  {
    id: 26,
    name: "Starfield",
    category: "action-rpg",
    price: 35,
    platform: "PC / Xbox Series X",
    year: "2023",
    developer: "Bethesda Game Studios",
    esrb: "M (Mature)",
    cpu: "Intel Core i7-6800K / AMD Ryzen 5 2600X",
    gpu: "NVIDIA GTX 1070 Ti / AMD RX 5700",
    ram: "16 GB RAM",
    storage: "125 GB available space",
    desc: "Starfield is the first new universe in over 25 years from Bethesda Game Studios. In this next-generation RPG set amongst the stars, create any character you want and explore with unparalleled freedom as you embark on an epic journey to answer humanity's greatest mystery.",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80",
    rating: 4.4,
    licensePattern: "SRFD-SPAC-ESHIP-UNIV-ERSE"
  },
  {
    id: 27,
    name: "STAR WARS Jedi: Survivor™",
    category: "action-rpg",
    price: 70,
    platform: "PC / PS5 / Xbox Series X",
    year: "2023",
    developer: "Respawn Entertainment",
    esrb: "T (Teen)",
    cpu: "Intel Core i7-7700 / AMD Ryzen 5 1400",
    gpu: "NVIDIA GTX 1070 / AMD RX 580",
    ram: "8 GB RAM",
    storage: "155 GB available space",
    desc: "The story of Cal Kestis continues in Star Wars Jedi: Survivor, a galaxy-spanning action-adventure game. Stand against the dark times of the Empire, mastering new lightsaber stances and force techniques.",
    image: "https://images.unsplash.com/photo-1593305841991-05c297ba4575?auto=format&fit=crop&w=800&q=80",
    rating: 4.6,
    licensePattern: "SWJS-CALK-ESTI-SFOR-CE24"
  },
  {
    id: 28,
    name: "FIFA 23",
    category: "sports",
    price: 20,
    platform: "PC / PS5 / PS4 / Xbox",
    year: "2022",
    developer: "EA Sports",
    esrb: "E (Everyone)",
    cpu: "Intel Core i5 6600k / AMD Ryzen 5 1600",
    gpu: "NVIDIA GTX 1050 Ti / AMD RX 570",
    ram: "8 GB RAM",
    storage: "50 GB available space",
    desc: "Experience the excitement of the world's game with HyperMotion2 Technology, both men's and women's FIFA World Cup tournaments, and cross-play features that unite fans.",
    image: "https://images.unsplash.com/photo-1579758629938-03607ccdbaba?auto=format&fit=crop&w=800&q=80",
    rating: 4.3,
    licensePattern: "FIFA-23EA-SPRT-WORL-DCUP"
  },
  {
    id: 29,
    name: "Forza Horizon 5",
    category: "sports",
    price: 35,
    platform: "PC / Xbox Series X / Xbox One",
    year: "2021",
    developer: "Playground Games",
    esrb: "E (Everyone)",
    cpu: "Intel Core i5-4460 / AMD Ryzen 3 1200",
    gpu: "NVIDIA GTX 970 / AMD RX 470",
    ram: "8 GB RAM",
    storage: "110 GB available space",
    desc: "Explore the vibrant, ever-evolving open world landscapes of Mexico with limitless, fun driving action in hundreds of the world's greatest cars.",
    image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    licensePattern: "FH5M-EXIC-ODRI-VEXP-LORE"
  },
  {
    id: 30,
    name: "NBA 2K25",
    category: "sports",
    price: 59,
    platform: "PC / PS5 / Xbox Series X",
    year: "2024",
    developer: "Visual Concepts",
    esrb: "E (Everyone)",
    cpu: "Intel Core i5-9600 / AMD Ryzen 5 3600",
    gpu: "NVIDIA GTX 1060 / AMD RX 580",
    ram: "8 GB RAM",
    storage: "150 GB available space",
    desc: "Compete your way in NBA 2K25 as you run your MyCAREER, customize your ultimate dream roster in MyTEAM, and dominate the court with pro-play realism.",
    image: "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=800&q=80",
    rating: 4.4,
    licensePattern: "NBA2-K25B-ASKT-BALL-MVP4"
  },
  {
    id: 31,
    name: "Ghost of Yotei",
    category: "action-rpg",
    price: 70,
    platform: "PS5",
    year: "2025",
    developer: "Sucker Punch Productions",
    esrb: "M (Mature)",
    cpu: "N/A (Console Dedicated)",
    gpu: "N/A (Console Dedicated)",
    ram: "16 GB RAM",
    storage: "80 GB available space",
    desc: "Set in 1603 Japan, follow the journey of Atsu, a female warrior seeking vengeance under the shadow of Mount Yotei in this breathtaking open-world samurai adventure.",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    licensePattern: "GOYT-ATSU-VENG-EANC-1603"
  },
  {
    id: 32,
    name: "Spider-Man 2",
    category: "action-rpg",
    price: 60,
    platform: "PS5",
    year: "2023",
    developer: "Insomniac Games",
    esrb: "T (Teen)",
    cpu: "N/A (Console Dedicated)",
    gpu: "N/A (Console Dedicated)",
    ram: "16 GB RAM",
    storage: "90 GB available space",
    desc: "Peter Parker and Miles Morales return for an exciting new adventure in the critically acclaimed Marvel's Spider-Man franchise. Swing, jump, and utilize the new Web Wings to travel across Marvel's New York.",
    image: "https://images.unsplash.com/photo-1608889174633-41a0c2439401?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    licensePattern: "SPID-ERM2-PETE-MILE-NYNY"
  },
  {
    id: 33,
    name: "Sekiro: Shadows Die Twice",
    category: "action-rpg",
    price: 30,
    platform: "PC / PS4 / Xbox One",
    year: "2019",
    developer: "FromSoftware",
    esrb: "M (Mature)",
    cpu: "Intel Core i3-2100 / AMD FX-6300",
    gpu: "NVIDIA GeForce GTX 760 / AMD Radeon HD 7950",
    ram: "4 GB RAM",
    storage: "25 GB available space",
    desc: "Carve your own clever path to vengeance in the award-winning adventure from developer FromSoftware, creators of Dark Souls. Take revenge. Restore your honor. Kill ingeniously.",
    image: "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    licensePattern: "SEKI-ROSH-ADOW-SDIE-TWIC"
  },
  {
    id: 34,
    name: "Monster Hunter Wilds",
    category: "action-rpg",
    price: 70,
    platform: "PC / PS5 / Xbox Series X",
    year: "2025",
    developer: "Capcom",
    esrb: "T (Teen)",
    cpu: "Intel Core i5-11600K / AMD Ryzen 5 5600X",
    gpu: "NVIDIA RTX 2070 Super / AMD RX 6700 XT",
    ram: "16 GB RAM",
    storage: "100 GB available space",
    desc: "The next generation of hunting action. Battle fearsome monsters in vast, dynamic ecosystems where weather changes the terrain, herding instincts shape the hunt, and your arsenal defines your legend.",
    image: "https://images.unsplash.com/photo-1612287230202-1bf1d85d1bdf?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    licensePattern: "MHWL-HUNT-WILD-MONS-TER8"
  },
  {
    id: 35,
    name: "Cyberpunk 2077: Phantom Liberty",
    category: "action-rpg",
    price: 30,
    platform: "PC / PS5 / Xbox Series X",
    year: "2023",
    developer: "CD Projekt Red",
    esrb: "M (Mature)",
    cpu: "Intel Core i7-12700 / AMD Ryzen 7 7800X3D",
    gpu: "NVIDIA RTX 3080 / AMD RX 6800 XT",
    ram: "16 GB RAM",
    storage: "35 GB (Requires Base Game)",
    desc: "Phantom Liberty is a spy-thriller expansion for Cyberpunk 2077. Return as cyber-enhanced mercenary V and embark on a high-stakes mission of espionage and intrigue to save the NUS President.",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    licensePattern: "CP77-PLIB-ERTY-SPYY-DOGT"
  },
  {
    id: 36,
    name: "Gran Turismo 7",
    category: "sports",
    price: 50,
    platform: "PS5 / PS4",
    year: "2022",
    developer: "Polyphony Digital",
    esrb: "E (Everyone)",
    cpu: "N/A (Console Dedicated)",
    gpu: "N/A (Console Dedicated)",
    ram: "16 GB RAM",
    storage: "110 GB available space",
    desc: "Whether you're a competitive or casual racer, collector, tuner, livery designer, or photographer – find your line with an staggering collection of game modes including fan-favorites like GT Campaign.",
    image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    licensePattern: "GT7R-ACING-SIMU-LATO-RPR0"
  },
  {
    id: 37,
    name: "UFC 5",
    category: "sports",
    price: 45,
    platform: "PS5 / Xbox Series X",
    year: "2023",
    developer: "EA Vancouver",
    esrb: "M (Mature)",
    cpu: "N/A (Console Dedicated)",
    gpu: "N/A (Console Dedicated)",
    ram: "16 GB RAM",
    storage: "60 GB available space",
    desc: "Powered by the Frostbite engine, EA Sports UFC 5 is the next evolution of combat sports video games. From unrivaled graphics upgrades to all-new damage systems and doctor stoppages.",
    image: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=800&q=80",
    rating: 4.4,
    licensePattern: "UFC5-MMAF-IGHT-KOCH-AMP5"
  },
  {
    id: 38,
    name: "Demon Slayer: The Hinokami Chronicles",
    category: "anime",
    price: 40,
    platform: "PC / PS5 / Xbox Series X",
    year: "2021",
    developer: "CyberConnect2",
    esrb: "T (Teen)",
    cpu: "Intel Core i5-3470 / AMD FX-8350",
    gpu: "NVIDIA GeForce GTX 760 / AMD Radeon R9 280",
    ram: "6 GB RAM",
    storage: "25 GB available space",
    desc: "Become the blade that destroys demons! In solo play mode, walk the path of Tanjiro Kamado whose family is slaughtered and sister transformed into a demon. Wield elemental combat skills in anime arena matchups.",
    image: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80",
    rating: 4.6,
    licensePattern: "DSYA-TANJ-IROO-BLAD-NEZU"
  },
  {
    id: 39,
    name: "Solo Leveling: Arise",
    category: "anime",
    price: 0,
    platform: "PC / Mobile (Android & iOS)",
    year: "2024",
    developer: "Netmarble",
    esrb: "T (Teen)",
    cpu: "Intel Core i5-4460 / AMD Ryzen 3 1200",
    gpu: "NVIDIA GTX 1050 / AMD RX 560",
    ram: "8 GB RAM",
    storage: "20 GB available space",
    desc: "Rise from the World's Weakest Hunter of E-Rank to the legendary Shadow Monarch! Unleash deadly slash combos, command shadow armies, and follow Jinwoo Sung's leveling journey in this gorgeous action RPG.",
    image: "https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    licensePattern: "SLAR-SUNG-JINW-OOMN-ARCH"
  },
  {
    id: 40,
    name: "Bleach: Rebirth of Souls",
    category: "anime",
    price: 50,
    platform: "PC / PS5 / Xbox Series X",
    year: "2025",
    developer: "Tamsoft / Bandai Namco",
    esrb: "T (Teen)",
    cpu: "Intel Core i5-8400 / AMD Ryzen 5 2600",
    gpu: "NVIDIA GTX 1060 / AMD RX 580",
    ram: "8 GB RAM",
    storage: "30 GB available space",
    desc: "Unleash your sword soul and reverse your fate in Bleach: Rebirth of Souls! Engage in intense sword duels featuring dramatic power sweeps, Bankai releases, and clash mechanics directly from the anime saga.",
    image: "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    licensePattern: "BROS-ICHG-BANK-AISS-SOUL"
  },
  {
    id: 41,
    name: "Naruto x Boruto Connections",
    category: "anime",
    price: 49,
    platform: "PC / PS5 / Xbox Series X / Switch",
    year: "2023",
    developer: "CyberConnect2",
    esrb: "T (Teen)",
    cpu: "Intel Core i7-4770 / AMD Ryzen 5 1400",
    gpu: "NVIDIA GTX 1060 / AMD RX 480",
    ram: "8 GB RAM",
    storage: "30 GB available space",
    desc: "Celebrate the 20th anniversary of Naruto's anime debut with the next exciting entry in the STORM series! Boasting the largest roster of characters in ninja history, play through major iconic fight scenes.",
    image: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80",
    rating: 4.6,
    licensePattern: "NXBC-NINJ-ACON-NECT-IONS"
  },
  {
    id: 42,
    name: "Silent Hill 2 Remake",
    category: "horror",
    price: 60,
    platform: "PC / PS5",
    year: "2024",
    developer: "Bloober Team",
    esrb: "M (Mature)",
    cpu: "Intel Core i7-8700 / AMD Ryzen 5 3600",
    gpu: "NVIDIA RTX 2080 / AMD RX 6800 XT",
    ram: "16 GB RAM",
    storage: "50 GB available space",
    desc: "Having received a letter from his deceased wife, James Sunderland returns to Silent Hill, a place filled with memories. Experience a masterclass in psychological survival horror with highly immersive graphics.",
    image: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    licensePattern: "SH2R-JAME-SJAM-MARY-HILL"
  },
  {
    id: 43,
    name: "Alan Wake 2",
    category: "horror",
    price: 50,
    platform: "PC / PS5 / Xbox Series X",
    year: "2023",
    developer: "Remedy Entertainment",
    esrb: "M (Mature)",
    cpu: "Intel Core i5-7600K / AMD Ryzen 5 3600",
    gpu: "NVIDIA RTX 3060 / AMD RX 6600 XT",
    ram: "16 GB RAM",
    storage: "90 GB available space",
    desc: "A string of ritualistic murders threatens Bright Falls, an idyllic small-town community. Saga Anderson, an FBI agent, arrives to investigate, while Alan Wake writes a dark story to shape reality.",
    image: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    licensePattern: "AW2X-SAGA-ANDE-RSON-WRIT"
  },
  {
    id: 44,
    name: "Resident Evil Village",
    category: "horror",
    price: 25,
    platform: "PC / PS5 / Xbox Series X",
    year: "2021",
    developer: "Capcom",
    esrb: "M (Mature)",
    cpu: "Intel Core i5-7500 / AMD Ryzen 3 1200",
    gpu: "NVIDIA GTX 1056 / AMD RX 560",
    ram: "8 GB RAM",
    storage: "50 GB available space",
    desc: "Experience survival horror like never before in the eighth major installment in the story franchise. Set a few years after the biohazard event, Ethan Winters is thrust into a new nightmare village populated by beasts and vampires.",
    image: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    licensePattern: "RE8V-ETHA-NWIN-TERS-DIME"
  },
  {
    id: 45,
    name: "Dead Space Remake",
    category: "horror",
    price: 30,
    platform: "PC / PS5 / Xbox Series X",
    year: "2023",
    developer: "Motive Studio",
    esrb: "M (Mature)",
    cpu: "Intel Core i5-8600 / AMD Ryzen 5 2600x",
    gpu: "NVIDIA GTX 1070 / AMD RX 5700",
    ram: "16 GB RAM",
    storage: "50 GB available space",
    desc: "The sci-fi survival horror classic returns, completely rebuilt from the ground up to offer a deeper and more immersive experience – featuring jaw-dropping audio-visual fidelity and terrifying gameplay.",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    licensePattern: "DS1R-ISAA-CCLA-RKKI-SHIM"
  },
  {
    id: 46,
    name: "The Outlast Trials",
    category: "horror",
    price: 35,
    platform: "PC / PS5 / Xbox Series X",
    year: "2024",
    developer: "Red Barrels",
    esrb: "M (Mature)",
    cpu: "Intel Core i5-6600 / AMD Ryzen 5 1500X",
    gpu: "NVIDIA GTX 1050 Ti / AMD RX 570",
    ram: "8 GB RAM",
    storage: "40 GB available space",
    desc: "Set in the Cold War era, human guinea pigs are involuntarily recruited by the Murkoff Corporation to test advanced methods of brainwashing. Work alone or with friends in terrifying survival scenarios.",
    image: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80",
    rating: 4.6,
    licensePattern: "TOUT-RIAL-MURK-OFFF-TEST"
  },
  {
    id: 47,
    name: "Free Fire: 1080 Diamonds Pack",
    category: "packages",
    price: 10,
    platform: "Mobile (Android / iOS)",
    year: "2026",
    developer: "Garena",
    esrb: "E (Everyone)",
    cpu: "N/A (Recharge)",
    gpu: "N/A (Recharge)",
    ram: "N/A (Recharge)",
    storage: "Instant Key Delivery",
    desc: "Instantly reload 1080 Diamonds into your Garena Free Fire account. Wield new gun skins, characters, custom bundles, and Elite Passes. Simply redeem the generated PIN code in-game.",
    image: "https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    licensePattern: "GFFF-1080-DMND-RECH-ARGE"
  },
  {
    id: 48,
    name: "PUBG Mobile: 660 UC Pack",
    category: "packages",
    price: 10,
    platform: "Mobile (Android / iOS)",
    year: "2026",
    developer: "Tencent Games",
    esrb: "E10+ (Everyone 10+)",
    cpu: "N/A (Recharge)",
    gpu: "N/A (Recharge)",
    ram: "N/A (Recharge)",
    storage: "Instant Key Delivery",
    desc: "Receive 660 Unknown Cash (UC) instantly in PUBG Mobile. Use it to purchase the current Royale Pass, unlock weapons crates, grab outfits, and access lucky spins.",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80",
    rating: 4.6,
    licensePattern: "PUBG-0660-UCCC-RECH-ARGE"
  },
  {
    id: 49,
    name: "Fortnite: 2800 V-Bucks Pack",
    category: "packages",
    price: 23,
    platform: "PC / Console / Mobile",
    year: "2026",
    developer: "Epic Games",
    esrb: "E (Everyone)",
    cpu: "N/A (Recharge)",
    gpu: "N/A (Recharge)",
    ram: "N/A (Recharge)",
    storage: "Instant Key Delivery",
    desc: "Add 2800 V-Bucks to your Epic Games account. Buy legendary outfits, pickaxes, wraps, gliders, emote animations, and Battle Passes. Works across LEGO Fortnite, Rocket Racing, and Festival.",
    image: "https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    licensePattern: "FORT-2800-VBCK-RECH-ARGE"
  },
  {
    id: 50,
    name: "F1 24",
    category: "sports",
    price: 60,
    platform: "PC / PS5 / Xbox Series X",
    year: "2024",
    developer: "Codemasters",
    esrb: "E (Everyone)",
    cpu: "Intel Core i3-2130 / AMD FX-4300",
    gpu: "NVIDIA GTX 1060 / AMD RX 480",
    ram: "8 GB RAM",
    storage: "80 GB available space",
    desc: "Be one of the 20 with EA SPORTS F1 24, the official video game of the 2024 FIA Formula One World Championship. Unleash your champion in pursuit of a legacy-defining Career.",
    image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80",
    rating: 4.5,
    licensePattern: "F124-FORM-ULA1-OFFI-CIAL"
  }
];

// Ensure this database is visible on window
if (typeof window !== 'undefined') {
  window.GAMES_DATA = GAMES_DATA;
}
